logging:
    pattern:
        console: "[Kafka Core Producer] %clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n"
spring:
    application:
        name: kafka-core-producer
    main:
        banner-mode: "off"
        log-startup-info: false 
    jackson:
        date-format: dd-MM-yyyy
    kafka:
        bootstrap-servers: localhost:9092
        properties:
            metrics:
                num:
                    samples: 3
